version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    logging:
        driver: none
    ports:
        - 5432:5432

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      SECRET_KEY: django-insecure-#04i-+45_0!#z@x616qo3@$$^k99gr&7c(ysz$$kqf$$a*_^ax^3i
    logging:
        driver: none
    ports:
      - 8000:8000
    depends_on:
      - db
